### PR TITLE
336 broadband refactor

### LINKED ISSUE #336: Create script for broadband data collection

### PR DESCRIPTION
**Pull request by dede95**
Closes #336

### CODE REVIEW

**Comment by mindrones** [comment]
The schema has changed after #365, please make sure to update this PR before merging.

**Review by mindrones — COMMENTED** [review]
I can't seem to find yaml files

**Comment by dede95** [comment]
> I can't seem to find yaml files

The yaml files are there! Just in the broadband processed data folder

**Review by mindrones — APPROVED** [review]
Gosh sorry you're right, I forgot this was a refactor :)

Good to merge for my part!

**Pull request merged**
